docs/geometry.rst, docs/index.rst, pygeos/__init__.py, pygeos/constructive.py, pygeos/creation.py, pygeos/geometry.py, pygeos/predicates.py, pygeos/set_operations.py, pygeos/test/common.py, pygeos/test/test_creation.py, pygeos/test/test_geometry.py, src/ufuncs.c
=> Document and test functions in geometry.py

setup.py, src/geos.h, src/pygeom.c, src/pygeom.h, src/ufuncs.c
This is an attempt to split the single (big) ufuncs C file in multiple files.
I find this a bit easier to understand the code if it is not all in a huge file, but it was also just a good exercise to get familiar with the code, so @caspervdw you certainly don't need to like this ;)
=> Split single ufuncs.c file in multiple files

.travis.yml, appveyor.yml, docs/index.rst, docs/linear.rst, pygeos/constructive.py, pygeos/linear.py, pygeos/test/common.py, pygeos/test/test_linear.py, src/geos.h, src/ufuncs.c
I think we might be heading to a next release. It is good to have the API docs finished then.
edit: I renamed some functions to stick with PostGIS namings, those are the namings most GIS experts know.
edit2: the shared_paths functions needs some additional attention (I think it should output 2 arrays or an Nx2 array of geometries), I removed it for now
=> Finish API docs

README.rst, docs/index.rst
- Some small fixes
- Added a note on the "state" of the package (you are ok with the wording?)
- Added a note on the relationship with Shapely (I wanted to at least have something about the difference between both)
=> Small updates to the README

src/geos.h, src/pygeom.h, src/ufuncs.h
@thomersch this might solve your issue #78
=> Add extern in header files

docs/index.rst, docs/strtree.rst, pygeos/__init__.py, pygeos/strtree.py, pygeos/test/common.py, pygeos/test/test_strtree.py, setup.py, src/kvec.h, src/lib.c, src/strtree.c, src/strtree.h
=> ENH: Add STRtree

MANIFEST.in
Supersedes  #99
The remaining work will be pushed over to [pygeos/pygeos-wheels](https://github.com/pygeos/pygeos-wheels).
=> ENH: Add any pygeos/*.dll files for Windows binary .whl files

docs/environment.yml
=> MAINT,DOC: change RTD channel to just 'defaults', pin versions

pygeos/test/test_creation.py, src/ufuncs.c
Closes #74 . I cannot reproduce locally, but maybe a CI picks it up
=> BUG: Check types in create_collections

pygeos/constructive.py, pygeos/test/test_constructive.py, src/ufuncs.c
xref https://github.com/pygeos/pygeos/issues/71
This is exposing `GEOSNormalize` (postgis equivalent: https://postgis.net/docs/ST_Normalize.html).
Questions:
- This is a "inplace" function in GEOS. Do we want to act it inplace as well in our python API? Otherwise I can first clone the geometry inside the ufunc function.
(still need to add tests)
=> ENH: add normalize

src/geos.h, src/ufuncs.c
Closes https://github.com/pygeos/pygeos/issues/143
=> Refactor GEOS_SINCE_3X0 to GEOS_SINCE_3_X_0

benchmarks/benchmarks.py
- IO operations (to and from WKT and WKB)
- Geometry construction
Addresses issue #109.
=> Add additional benchmarks

src/strtree.c
Adresses #161. Error made in #144, which is luckily not yet released.
=> Fix memleak in strtree creation (introduced in #144)

src/ufuncs.c
=> Fix memory leak in from_shapely (introduced in #144)

CHANGELOG.rst, pygeos/test/test_io.py, src/geos.c, src/geos.h, src/pygeom.c, src/ufuncs.c
Closes #134 
It still seems to segfault with GEOS 3.8
=> [Done] Raise ValueError on to_wkt of multipoint with empty point

pygeos/test/test_creation.py, src/geos.h, src/ufuncs.c
=> Fix segfault on linestring/linearring/polygon creation

CHANGELOG.rst, pygeos/constructive.py, src/ufuncs.c
=> Accept multi geometries in boundary()

CHANGELOG.rst, pygeos/predicates.py, pygeos/test/test_predicates.py, src/ufuncs.c
=> Implement is_ccw for GEOS >= 3.7.0

pygeos/linear.py, pygeos/test/test_linear.py, src/geos.c, src/geos.h, src/ufuncs.c
=> Fix line_interpolate_point for multilinestrings

CHANGELOG.rst, pygeos/test/test_linear.py, src/ufuncs.c
=> BUG: Fix error handling for line_locate_point (GEOSProject(Normalized))

pygeos/measurement.py, pygeos/test/test_measurement.py, src/ufuncs.c
Longer explanation of what the method does: https://locationtech.github.io/jts/javadoc/org/locationtech/jts/precision/MinimumClearance.html (not sure to what extent we can copy explanations to our docstrings ..)
=> ENH: add minimum_clearance

CHANGELOG.rst, pygeos/constructive.py, pygeos/test/test_constructive.py, src/ufuncs.c
=> ENH: offset_curve

src/ufuncs.c
https://github.com/pygeos/pygeos/pull/156 added quite some code to get the GIL release working with geometry creating ufuncs. I think we can improve maintainability a bit by factoring out some of the parts into additional macros.
=> CLN: deduplicate some code with macros in geometry-creating ufuncs

CHANGELOG.rst, pygeos/constructive.py, pygeos/test/test_constructive.py, src/ufuncs.c
=> ENH: Adds reverse function for GEOS >= 3.7

CHANGELOG.rst, benchmarks/benchmarks.py, pygeos/constructive.py, pygeos/test/test_constructive.py, src/ufuncs.c
(we could certainly make xmin/ymin/xmax/ymax accept arrays as well, but didn't include that for a first pass)
=> ENH: clip_by_rect

pygeos/test/test_io.py
Small mistake I did in https://github.com/pygeos/pygeos/pull/269
=> TST: fix from_shapely test for numpy 1.20

CHANGELOG.rst, pygeos/creation.py, pygeos/predicates.py, pygeos/test/test_predicates.py, src/pygeom.c, src/ufuncs.c
=> ENH: Add is_prepared

CHANGELOG.rst, pygeos/constructive.py, pygeos/test/test_constructive.py, src/ufuncs.c
There is also `polygonize_full` to add
I am not sure the ufunc version will be that useful (since with a 2D array, you need the same number of lines for each entry). But most consistent to expose it this way of course.
=> ENH: add polygonize ufunc

CHANGELOG.rst, pygeos/constructive.py, pygeos/test/test_constructive.py, src/geos.h, src/ufuncs.c
This adds `GEOSDensify`, which will be available when GEOS 3.10.0 is released; currently available on GEOS `master`.
crossref to Shapely issue: https://github.com/Toblerity/Shapely/issues/1037
/cc @snowman2
=> ENH: Add densify ufunc

pygeos/predicates.py
resolves #287 
The term `dimension` is prominent here (area, line, or point), but may cause confusion compared to coordinate dimensions (2D or 3D).  Does it need further clarification here?
=> DOC: clarify overlaps versus crosses predicates

CHANGELOG.rst, pygeos/creation.py, pygeos/test/test_creation.py, src/ufuncs.c
=> [Done] Fix creation error handling and release GIL

.github/workflows/test-conda.yml, .github/workflows/test-linux.yml, .travis.yml, appveyor.yml
=> Only run doctests on conda-forge, latest Py38

pygeos/constructive.py, pygeos/creation.py, pygeos/geometry.py, pygeos/io.py, pygeos/linear.py, pygeos/measurement.py, pygeos/predicates.py, pygeos/set_operations.py
This adds `**kwargs` forwarding to ufuncs where missing.
Also I wanted to document this on each function. I did one (`boundary`), what do you think? 
https://pygeos--327.org.readthedocs.build/en/327/constructive.html#pygeos.constructive.boundary
=> [Done] Add kwargs where necessary and document it

.github/workflows/lint.yml, .pre-commit-config.yaml
Follow-up on https://github.com/pygeos/pygeos/pull/328
=> Add pre-commit configuration

pygeos/coordinates.py
=> DOC: clarify that set_coordinates modifies array of geometries in place

.github/workflows/test-conda.yml, .github/workflows/test-linux.yml, .travis.yml, CHANGELOG.rst, appveyor.yml, docs/conf.py, pygeos/constructive.py, pygeos/decorators.py, pygeos/geometry.py, pygeos/set_operations.py, pygeos/test/test_misc.py, pyproject.toml, setup.py
=> Show docstrings for functions decorated with requires_geos

src/ufuncs.c
=> BUG: fix no inplace output check for box and set_precision

.github/workflows/release.yml, pyproject.toml
Resolves https://github.com/pygeos/pygeos/issues/384 @caspervdw Could you please review this PR?
=> Add linux aarch64 wheel build support

setup.py
https://www.python.org/dev/peps/pep-0632/
=> REF: Use pkg_resources instead of distutils

.github/workflows/test-pip.yml, ci/install_geos.sh
=> [Done] Fix GEOS main caching

CHANGELOG.rst, pygeos/geometry.py, pygeos/predicates.py, pygeos/tests/common.py, pygeos/tests/test_coordinates.py, pygeos/tests/test_geometry.py, src/coords.c, src/geos.c, src/geos.h, src/ufuncs.c
This is a first step to addressing #323 .
=> [Done] Force 2D/3D

CHANGELOG.rst, pygeos/geometry.py, pygeos/io.py, pygeos/tests/test_io.py, src/geos.c, src/geos.h, src/pygeom.c, src/ufuncs.c
This is a (hopefully) temporary fix for the 3D point serialization. See https://trac.osgeo.org/geos/ticket/1129
=> [Done] Fix 3D empty WKT serialization

.github/workflows/release.yml, CHANGELOG.rst, pyproject.toml
=> [Done] OSX arm64 and universal2 wheels

CHANGELOG.rst, pygeos/tests/test_strtree.py, src/strtree.c
=> Fix error handling in STRtree

CHANGELOG.rst, pygeos/_geometry.pyx, pygeos/creation.py, pygeos/tests/test_creation.py, pygeos/tests/test_creation_indices.py, src/ufuncs.c
=> Change linearring closing logic

pygeos/creation.py, pygeos/geometry.py, pygeos/io.py
Closes #289, Closes #397, Closes #424
=> Documentation fixes

README.rst, ci/wheelbuilder/LICENSE_GEOS
Closes https://github.com/pygeos/pygeos/issues/433
=> Update GEOS url

README.rst
@jorisvandenbossche  What do you think? When this is in, I'll release 0.12.
=> Adjust readme

.github/workflows/test-pip.yml, .pre-commit-config.yaml, pygeos/tests/test_measurement.py
Currently failing, see https://stackoverflow.com/questions/71673404/importerror-cannot-import-name-unicodefun-from-click
=> CI: update black version

.github/workflows/lint.yml, .github/workflows/release.yml, .github/workflows/test-pip.yml, .pre-commit-config.yaml, CHANGELOG.rst, pygeos/tests/test_constructive.py, pygeos/tests/test_creation.py, pygeos/tests/test_io.py, pyproject.toml, setup.py, src/ufuncs.c
Ports of shapely PRs (by @jorisvandenbossche):
- https://github.com/shapely/shapely/pull/1388
- https://github.com/shapely/shapely/pull/1654
- https://github.com/shapely/shapely/pull/1647
I am aiming for a maintenance release, just bumping to the next micro tag of GEOS (3.10.4) and add Py3.11 support.
=> [Done] Build Py3.11 wheels & fix tests for GEOS 3.11
