src/ufuncs.c
This doesn't fix any build issue I am having (I thought for a moment this would fix a conda-forge problem, but it seems not to fix it), but, from seeing other projects (arrow, pandas), this seems to be the way they include numpy (look on the canonical include dirs, not first in the local directory).
=> BLD: use angle bracket include for numpy

pygeos/__init__.py, pygeos/constructive.py, pygeos/creation.py, pygeos/geometry.py, pygeos/linear.py, pygeos/measurement.py, pygeos/predicates.py, pygeos/set_operations.py, setup.py, src/geos.c, src/geos.h, src/lib.c, src/pygeom.c, src/pygeom.h, src/ufuncs.c, src/ufuncs.h
@caspervdw I started this afternoon to try to split the files a bit more and have a separate ufuncs file and a general `lib` module instead of `ufuncs` (since not everything are ufuncs, I think mentioned it before on some PR, not sure if you are OK with that?).
Then I saw that you also did some changes to move out geos things into geos.c / pygeom.c in the coordinates PR, and included that here as well to see if all is working.
One thing that I ran into is that the ufunc registry functions don't copy the passed arguments, and you need to ensure that all those objects are kept alive as long as the ufunc objects exist. That caused segfaults when calling `init_ufuncs` defined in `ufuncs.c` from `lib.c` (as all those arguments where not declared in ufuncs.h, only the init function, I suppose). …
=> Refactor ufuncs module into lib module

pygeos/__init__.py, pygeos/io.py, pygeos/test/test_creation.py, pygeos/test/test_geometry.py, pygeos/test/test_io.py, pygeos/test/test_readers_writers.py, src/pygeom.c, src/ufuncs.c
Start for adding from_wkt / to_wkt / from_wkb / to_wkt ufuncs.
They are right now already defined on the Geometry object, but those are useful as ufuncs as well. 
We can probably remove the implementation in pygeom.c to avoid duplication. But the question is whether we want to keep those as methods in the public API?
I should maybe also move this into a separate .c file, as the ufuncs.c is starting to become quite long? (although it are ufuncs)
Still need to make the nice Python functions, only the barebone ufuncs for now for the readers. 
Also still need to do proper error handling (ensure that I destroy the reader when there is an error)
=> ENH: add wkt / wkb ufuncs

pygeos/predicates.py, pygeos/test/test_predicates.py
This adds a `equals_exact` predicate. 
I thought the python wrapper for the ufunc was missing for this one, so added it to `predicates.py`, but only then saw that it is actually exposed through `equals` with a tolerance argument. 
But since I already did the work, directly opening the PR instead of an issue.
I would argue that it is better to have a separate `equals_exact` instead of combining it in `equals`:
- There are doing something different: spatial equality (based on the DE-9IM model) vs exact coordinate equality. Therefore, there are some differences between both functions to be aware of as a user (eg different ordering of interiors or different direction of the ring). It's not just adding `tolerance` to the `equals` (eg `equals_exact(.., tolerance=0)` is not the same as …
=> ENH: add equals_exact predicate

src/coords.h, src/geos.h
This also reduces the number of warnings a bit, as many of the "function declaration isn’t a prototype" were coming from the non-reentrant declarations in geoc_c.h
=> Ensure to only use GEOS reentrant API

pygeos/measurement.py, pygeos/test/test_measurement.py, src/ufuncs.c
I did not use the MinX etc. functions from the GEOS C-API, because:
- each of these 4 functions construct the envelope
- these functions are not available in GEOS 3.5
Instead, I construct the envelope and extract the coordinates from it.
=> [ENH] Add bounds function

pygeos/__init__.py, pygeos/io.py, pygeos/test/test_io.py, pygeos/test/test_misc.py, src/lib.c, src/pygeom.c, src/ufuncs.c
Following discussions in #47 and #54 
@jorisvandenbossche  I took the ufunc approach, and implemented some checks. I think 'segfault and memoryleak protection' is now as good as shapely. 
Conversion of a list of 10000 shapely geometries takes 4 ms with this function. against 120 ms going through WKB.
=> ENH: Implement from_shapely

pygeos/linear.py, pygeos/test/test_linear.py, src/ufuncs.c
This PR reintroduce the function `pygeos.shared_paths()` as was discussed in https://github.com/pygeos/pygeos/issues/73.
The `shared_paths()` function returns a `pygeos.Geometry GEOMETRYCOLLECTION`. 
To access the shared paths that have the same direction in both inputs use index 0 in `pygeos.get_geometry()` using the result of `shared_paths()` and use index 1 to access the shared paths that have the opposite direction.
=> Reintroduce shared_paths

src/strtree.h
This fixes #89 theoretically.
The `strtree.h` file currently *defines* the symbol STRtreeType. Adding `extern` instead just *declares* STRtreeType, which is what you should do in a header file. Same issue as in #79 
I was looking for a gcc / ld flag that would detect this issue, to add on Travis so that I don't keep making this mistake. 
@sgillies please check if this works for you
=> Fix strtree header file 

docs/strtree.rst, pygeos/strtree.py, pygeos/test/test_strtree.py, src/strtree.c
This PR adds support for several geometric predicates into the STRtree `query()` function.  In addition to querying geometries from the tree that have envelopes that intersect the envelope of the input geometry, this now allows you to test the predicate relationships between the input geometry and the returned geometries from the tree:
* `intersects`
* `within`
* `contains`
* `overlaps`
* `crosses`
* `touches`
This intentionally does not include other binary predicates, since they don't seem useful in this context (e.g., `disjoint`).
This should make it easier to implement spatial joins on top of `pygeos`.
This could be further improved by using prepared geometries and vectorizing the query function, but those should be handled in a separate PR.
Most of the code here is in tests, to …
=> ENH: include predicates in STRtree.query()

pygeos/measurement.py, pygeos/test/test_measurement.py
As mentioned in #69, `total_bounds` was deferred for later work.  I needed it, so it was a good time to add.
It collapses all dimensions down to `xmin, ymin, xmax, ymax` regardless of the shape of arrays passed to `total_bounds`.
If any inputs are `None`, empty, or otherwise returns `[nan, nan, nan,nan]` for their bounds, `total_bounds` returns `[nan, nan, nan,nan]`.
I consolidated the tests for `bounds` and added counterparts for `total_bounds`
=> ENH: Added total_bounds()

pygeos/strtree.py, pygeos/test/test_strtree.py, src/strtree.c, src/strtree.h
This reproduces #97  locally
It seems like we need to keep references to the geometries that were used to construct an STRTree.
=> Fix segfault in strtree test_flush_geometries

pygeos/test/common.py, pygeos/test/test_geometry.py, src/pygeom.c, src/ufuncs.c
This implement hashing for geometry objects.
=> ENH: Implement hash, eq, neq

pygeos/strtree.py, pygeos/test/test_strtree.py, src/strtree.c
This adds a first pass at bulk query against `STRtree` instance, as the core of a spatial join function for #52.
This extends the functionality of the existing `STRtree::query()` method to handle multiple input geometries.  It returns a tuple of source (left) indexes and target (right) indexes that either overlap the windows of the sources, or also meet the predicate function provided.
Example:
```
tree = pygeos.STRtree(pygeos.points(np.arange(10), np.arange(10)))
tree.query_bulk([pygeos.points(1, 1)])
```
Multiple source geometries, first and third boxes overlap windows:
```
tree.query_bulk([
pygeos.box(0,0, 1,1), 
pygeos.box(100,100,110,110), 
pygeos.box(2,2,4,4)
])
```
This preserves the original `query()` function as a singular operation.
/cc: @jorisvandenbossche
=> ENH: query tree with multiple input geometries

src/geos.h, src/pygeom.c, src/ufuncs.c
This wraps the import of `geos_c.h` to silence GCC warnings coming from GEOS (not under our control).
It also fixed 2 minor compiler warnings in code here.
=> Remove compiler warnings

GEOS_LICENSE, MANIFEST.in, README.rst, setup.py
I read up on the LGPL 2.1 and in section 6 it is basically listed that we have to supply the LGPL license + refer to it in the docs.
There is no copyright notice in GEOS so we can't put that in our readme. (I grepped `opyright` in the whole geos distribution)
As we use dynamic linking, section 6b applies and we do not have to do anything more.
=> Include GEOS license info

docs/creation.rst, docs/index.rst, docs/io.rst
Added `pygeos.creation` and `pygeos.io` modules to API reference.
Closes #133
=> DOC: add missing modules

pygeos/constructive.py, pygeos/test/test_constructive.py, src/ufuncs.c
Firstly, great work with the project, team! I am excited about the Shapely 2.0 project, wanted to contribute where I can, and learn something along the way. @jorisvandenbossche suggested that https://github.com/pygeos/pygeos/issues/126 is good place to start. So this PR is me taking a stab at implementing one of the functions from the list. If this looks good, I can work on others too. Would love your feedback.
**Some relevant links**
- GEOS BuildArea documentation - https://geos.osgeo.org/doxygen/classgeos_1_1operation_1_1polygonize_1_1BuildArea.html#details
- PostGIS ST_BuildArea - https://postgis.net/docs/ST_BuildArea.html
=> Implement GEOSBuildArea_r under constructive.build_area (GEOS 3.8.0+)

pygeos/test/test_strtree.py, src/strtree.c
This changes the implementation of STRtree to omit any empty geometries when constructing the tree.
* all inputs (including `None`, empty geometries) are still available in the `tree.geometries()` ndarray
* `_geoms` at the C level is used for predicate tests only, and only includes non-empty geometries.  Since empty geometries are never returned from a tree query, their absence here is a non-issue.
* only significant change: `len(tree)` is now the count of all non-empty / non-`None` geometries; previously it was the count of all non-`None` geometries.
This adds additional tests for empty geometries and other variations in constructing / querying the tree.
Prior to this change, empty geometries would result in segfaults for GEOS <= 3.6.
=> ENH: only add non-empty geometries to STRtree

pygeos/measurement.py, pygeos/test/test_measurement.py, src/ufuncs.c
Code is pretty much similar to the implementation of wrappers for Hausdorff distance, except for:
1. Fréchet distance is only supported in 3.7.0, hence appropriate checks are additionally added.
2. When testing Hausdorff distance, there are tests with empty linestrings, but in the case of Fréchet distance, the GEOS library seems to be segfaulting when such inputs are passed. Hence I have skipped tests with empty linestrings for now. Any alternate suggestions over this are welcome.
Also, this is part of #126.
=> Implement wrappers for Fréchet distance under measurement module (3.7.0+)

pygeos/measurement.py, pygeos/test/test_measurement.py, src/ufuncs.c
Pretty straightforward change. I noticed 'hausdorff' was misspelled as 'haussdorf' in a few places while working on my previous PR https://github.com/pygeos/pygeos/pull/144, making it hard to be discovered through Ctrl+F.
=> Fix typo in haussdorf -> hausdorff

pygeos/constructive.py, pygeos/creation.py, pygeos/geometry.py, pygeos/linear.py, pygeos/set_operations.py, pygeos/test/test_set_operations.py, src/ufuncs.c
This addresses #155 , now only for the geometry-to-geometry operations (like `envelope` and `convex_hull`)
The same pattern could be repeated for all other geometry-creating operations.
=> Release the GIL for geometry-creating operations

.dockerignore, README.rst, docker/Dockerfile.valgrind
Valgrind is a C utility to track memory leak issues. See description of how to use the included docker in the README.
Currently, 322 out of 1124 tests are failing, so we have some work to do! I'll go through the logs and make separate issues.
The whole run takes 20 minutes so I did not make it part of the CI.
=> Memory leak testing using valgrind

CHANGELOG.rst, pygeos/test/test_creation.py, src/ufuncs.c
Closes #153 
Bug introduced in #86
=> FIX: Accept linearrings in pygeos.multilinestrings 

CHANGELOG.rst, pygeos/set_operations.py, pygeos/test/test_set_operations.py, src/ufuncs.c
Implement `GEOSCoverageUnion_r` under `set_operations`, while keeping the module API similar to others, by introducing two functions `coverage_union` and `coverage_union_all`. With the latter being a reducer function of the former.
The only slightly hacky thing is that I had to test `coverage_union` slightly different from other functions of the set operations module, as it is different from them, added a comment about this in code.
See related issue https://github.com/pygeos/pygeos/issues/126.
=> Implement GEOSCoverageUnion_r under set_operations (GEOS 3.8.0+)

README.rst
Small fix in the added text about Shapely RFC, otherwise it doesn't render correctly
=> Fix spacing in README

CHANGELOG.rst, pygeos/geometry.py, pygeos/test/test_geometry.py, src/ufuncs.c
I just noticed a small inconsistency with the GEOS API. In GEOS it is `GEOSGeom_getCoordinateDimension` (without trailing "s"), while in pygeos we have `get_coordinate_dimensions` (plural). 
Since our names are mostly based on GEOS' names, I *suppose* this inconsistency was an oversight (unless @caspervdw there is a reason for it?)
BTW, in PostGIS they abbreviate this to [`ST_CoordDim`](https://postgis.net/docs/ST_CoordDim.html) (and have an additional alias [`ST_NDims`](https://postgis.net/docs/ST_NDims.html)), but I think writing it in full is fine for us.
=> Rename get_coordinate_dimension (dimensions -> dimension)

CHANGELOG.rst, pygeos/geometry.py, pygeos/test/test_geometry.py, src/ufuncs.c
Adding a `pygeos.get_z` ufunc (in addition to `get_x` and `get_y`).
One open question might be what to return when the Point only has 2 dimensions. I originally thought to raise an error (see the commented code in the ufunc), but it seems that GEOS is not erroring on this but returning NaN, and we already return NaN as well for non-point geometries. 
On the other hand, I like the information to the user from raising an error in this case (eg for Shapely's `Point().z` attribute, we can certainly keep raising, even if the ufunc here would return NaN).
=> ENH: Add get_z ufunc

pygeos/io.py
I ran into circular import problems when using this in my shapely refactor that registers shapely classes for the Geometry subclasses (and the reason I am still using this is to get the part of shapely that I didn't refactor yet working, so having a temporary mix of pygeos and shapely's LGEOS ctypes methods)
=> Delay shapely import for from_shapely

CHANGELOG.rst, pygeos/constructive.py, pygeos/linear.py, pygeos/test/test_io.py, src/pygeom.c
=> Limit WKT length in repr

CHANGELOG.rst, docs/geometry.rst, pygeos/io.py, pygeos/test/test_io.py, src/pygeom.c
Closes #46
After a failed approach with `__getstate__` and `__setstate__`, I chose for the `__reduce__` route. `__setstate__` does not play  nice with the fact that our geometry objects are immutable. Further reading: https://docs.python.org/3/library/pickle.html#pickling-class-instances
`__reduce__` should return a tuple (callable, args). A convenient way for us would be the following:
- `(pygeos.lib.Geometry, ("<WKT>", ))`
However, WKT serialization is less efficient than WKB serialization. We could opt for:
- `(pygeos.lib.from_wkb, (b"<WKB>", ))`
When testing these approaches, a noticed that both of them have drawbacks.
- WKT does not support SRID serialization and it has an issue with empty points in multipoints (#171).
- WKB does not support linearrings
I am still in favour of going …
=> Support pickling

pygeos/geometry.py, pygeos/test/test_coordinates.py, pygeos/test/test_geometry.py, src/coords.c
This confirms that #196 was indeed solved in master by #190 . The test however uncovered another bug in `set_coordinates`, it raised a GEOSException when setting coordinates on an empty point.
Also, I cleaned up the old `NAG` geometrytype (we use `None` for that since a long time)
=> Fix bug when setting coordinates on an empty point

setup.py
This is an environment variable that Shapely currently allows setting (and uses on its CI), see https://github.com/Toblerity/Shapely/pull/983#issuecomment-699532587
=> BLD: allow GEOS_CONFIG env variable to override PATH

CHANGELOG.rst, pygeos/linear.py
This PR renames the argument `normalize` to `normalized` for `line_locate_point` and `line_locate_point` linear referencing functions. This brings the argument name in-line with Shapely (see [object.interpolate](https://shapely.readthedocs.io/en/stable/manual.html#object.interpolate) and [object.project](shapely.readthedocs.io/en/stable/manual.html#object.project)) and the underlying GEOS functions `GEOSProjectNormalized_r` and `GEOSInterpolateNormalized_r`.
=> Rename normalize -> normalized in linear referencing functions

.travis.yml
Python 3.5 is now no longer supported.  Pulled this change from #210 plus drop special handling for `pytest`.
=> Drop Python 3.5 from Travis-CI matrix

pygeos/test/test_constructive.py
I tested the new OverlayNG a while ago, and we only had 2 failures related to `make_valid`. But both are just a change in coordinate order and solved by using spatial equality or normalizing the resulting and expected multipolygon first.
=> TST: Fix make_valid tests for OverlayNG (normalize result/expected)

.travis.yml, appveyor.yml, ci/install_geos.cmd, ci/install_geos.sh, pygeos/test/test_misc.py
* Move away from conda, which does not offer many versions of GEOS
* Build and cache GEOS for Travis CI and AppVeyor
* Test Python 3.5 and GEOS 3.5.2
* Test Python 3.6, GEOS 3.6.4, and NumPy 1.13.3
* Test Python 3.7, GEOS 3.7.3, and NumPy 1.15.4
* Test Python 3.8, GEOS 3.8.1, and NumPy 1.17.5
* Test Python 3.9, GEOS 3.8.1, and NumPy 1.19.4
* Test Python 3.9-dev, GEOS master, and NumPY pre-release (Travis CI only)
* Skip `test_geos_capi_version` for GEOS 3.7.x on Windows due to GEOS issue
Supersedes #212
<s>Future considerations could also mix a few versions of NumPy too.</s> Updated to mix NumPy versions.
Also, this PR currently drops osx from the Travis CI testing. Is it worth keeping? It would require a bit more work if this is desired.
=> TST: Use native CI build tools to allow flexible GEOS versions

docs/environment.yml
This should fix our build at readthedocs
Also I redid the github integration and granted the RTD app access to update the status of projects in the pygeos organisation. The success (or failure) of the RTD build should now appear at each pull request (including this one).
See https://docs.readthedocs.io/en/stable/guides/autobuild-docs-for-pull-requests.html#features for further reading.
=> Add Cython to RTD build

.github/workflows/test-conda.yml, README.rst
Following #222 and #219, I think we should drop the older windows tests. They are covered by appveyor.
Also I shortened the name so that you can see the differences between builds in the Github status reports below a PR.
=> CI: Cull windows tests and shorten name

CHANGELOG.rst, pygeos/coordinates.py, pygeos/test/test_coordinates.py, src/coords.c
Closes #131
Building further upon https://github.com/pygeos/pygeos/pull/178, which already added this to `get_coordinates`, expanding to `set_coordinates`/`apply`. 
For `set_coordinates`, I didn't add a keyword, because there you can know it from the shape of the supplied coordinates array.
=> ENH: support z-coordinates in apply (coordinate transformation)

CHANGELOG.rst, appveyor.yml, pygeos/geometry.py, pygeos/test/test_geometry.py, src/ufuncs.c
Resolves #218  
Resolves #234
Previously, `get_num_geometries`, `get_num_coordinates`, `get_num_points`, `get_num_interior_rings` returned -1 for non-geometry values (`None`).
This changes the API to return 0 instead, which is more appropriate for counting type functions, since users may sum these values to perform subsequent operations as noted in #218, #197.
The only previously-stated return value that is changed here is for `get_num_coordinates`; the return value was not previously declared in docstrings for the other functions and -1 is likely unexpected for them.
=> API change: return 0 for None values in geometry counting functions

CHANGELOG.rst, pygeos/test/test_strtree.py, src/strtree.c
Resolves #235 
The overall strategy is to fetch both the original and prepared geometry from the `GeometryObject`, and only prepare internally within `evaluate_predicate` if not previously prepared.
Checked with valgrind to make sure we're not leaving prepared geometries around accidentally.
I discovered and corrected an autoformatting issue with the doc string for `evaluate_predicate`, hence the larger number of lines changed (the autoformatter previously rolled all params into single paragraph, to avoid this I made them separated by lines).
=> Integrate previously prepared geometries into STRtree query / bulk query

pygeos/_geometry.pyx
This removes code from `get_parts` Cython implementation no longer necessary after #220
=> CNL: Remove unnecessary filtering of counts from get_num_geometries

CHANGELOG.rst, pygeos/set_operations.py, pygeos/test/test_set_operations.py, src/ufuncs.c
Closes #37. API changes:
- `intersection_all` and `symmetric_difference_all` now ignore None values, rather than returning None if any value is None
- `union_all` (instead of `GEOMETRYCOLLECTION EMPTY`) now returns None if all input values are None
Memory-leak tested with valgrind.
=> FIX: Consistent behaviour for all reduction set_operations

src/lib.c
Non-releases of GEOS have `geos_c.h` headers like this:
```
#define GEOS_VERSION_PATCH 0beta1
```
which cannot be compiled, as this was expected to be an integer, not a string. This PR declares a quoted macro variable (using [this trick](https://stackoverflow.com/a/6671729/)), and takes the first substring to be the assumed patch digit. Theoretically, there could be more than one digit, but I don't think I've seen this from GEOS' history, so we could assume it will only be one character length.
Review carefully, as I seldom write C.
---
After this is merged, it should be possible to set `GEOS_VERSION: 3.9.0beta1` for CI testing along-side Python 3.9, similar to https://github.com/Toblerity/Shapely/pull/1041
=> FIX: handle non-integer GEOS_VERSION_PATCH like 0beta1 as 0

setup.py, src/strtree.c, src/strtree.h, src/vector.c, src/vector.h
This moves resizeable vector-related typedefs and functions to `vector.h` / `vector.c` for more generalized use elsewhere.  These currently were defined within strtree, which was their only use so far.
However, for #244 and likely other functions over the long term, we will need more general access to these so that we can build up vectors at runtime.
Types and functions renamed slightly for better clarity (I hope!).
=> CLN: Migrate resizeable vector types and functions to dedicated files

benchmarks/benchmarks.py
Adds basic benchmarks of STRtree query bulk functionality against polygons.
On my local machine, this shows:
```
time_tree_create                                                                                 4.47±0.4μs
time_tree_query_bulk                                                                             3.39±0.5μs
time_tree_query_bulk_contains                                                                      67.6±4ms
time_tree_query_bulk_contains_properly                                                          1.04±0.06ms
time_tree_query_bulk_covered_by                                                                    51.2±6ms
time_tree_query_bulk_covers                                                                        65.0±3ms
time_tree_query_bulk_crosses …
```
=> ENH: Add STRtree benchmarks

src/strtree.c, src/strtree.h, src/vector.h
Supersedes #261.
See #261 for a more complete description of the underlying issue with how we were adding indexes of geometries from the input array of the tree to the item data for each GEOSGeometry added to the STRtree.  The problem was that we were providing the address of a local integer in a loop.
In order to avoid adding a second array to track these indices, this PR instead makes a few adjustments:
* tree geometries are managed as an array on the tree (instead of resizeable vector); their size is known in advance, and this allows us to calculate pointer offsets to determine item indices
* the address of the pointer to `GeometryObject` in this array is then added to the item data for each `GEOSGeometry` added to the tree
* for any geometries that match the tree, we add this address …
=> ENH: STRtree: use addresses of tree geometries to calculate their index

CHANGELOG.rst, pygeos/geometry.py, pygeos/test/test_geometry.py, src/ufuncs.c
This adds get / set precision functions.
A few things to be aware of:
The Default value for `preserve_topology` is `False` to match simplify function; however, in GEOS it defaults to `True`; the choice was out of consistency, but it may well be appropriate to match GEOS.
There may be a couple GEOS bugs discovered in the tests here: 
1. geometrically invalid inputs do not behave as expected with `preserve_topology = True` (we get back only one of the polygons in the expected multipolygon).
2. polygons always collapse to empty polygons regardless of `keep_collapsed` even though linear rings are preserved.
Will need to dig into GEOS a bit more and log bugs there if appropriate.
I did not yet add additional tests to trace the precision through intersection, etc operations to verify the …
=> ENH: Add get / set precision ufuncs

pygeos/_geometry.pyx, pygeos/constructive.py, pygeos/coordinates.py, pygeos/geometry.py, pygeos/io.py, pygeos/measurement.py, pygeos/strtree.py, pygeos/test/test_coordinates.py, pygeos/test/test_io.py, pygeos/test/test_predicates.py
Closes https://github.com/pygeos/pygeos/issues/268
Mostly fixing warnings. In addition (the example shown in #268), the `from_shapely` function was broken in case the input was a list-like (not already an array, or not a scalar geometry)
=> Update for compatibility with numpy 1.20 (builtin type aliases, array coercion)

.github/workflows/test-conda.yml, .github/workflows/test-linux.yml, pygeos/constructive.py
GEOS 3.9.0 is already released a while, so adding it to the Linux github actions builds. 
In addition, it was added to conda-forge a few days ago, so I think it should automatically be picked up for the "GEOS latest" builds using the conda-forge channel in the conda github action builds.
=> CI: add GEOS 3.9.0 build to linux CI

CHANGELOG.rst, pygeos/set_operations.py, pygeos/test/test_set_operations.py, src/ufuncs.c
Closes #194
This was not as easy as expected. I got the error that I could not reduce over multiple axes because the array elements were not reorderable for this operation. I traced that back to the numpy source:
https://github.com/numpy/numpy/blob/5cae51e794d69dd553104099305e9f92db237c53/numpy/core/src/umath/reduction.c#L207
https://github.com/numpy/numpy/blob/509b5ae4a7bb3c99324fd302ead1bbf4b130c741/numpy/core/src/umath/ufunc_object.c#L3637
https://github.com/numpy/numpy/blob/4d290795d4e8c60053eb789acf173159dc4c1575/numpy/core/src/umath/ufunc_object.c#L2445
It appears to be undocumented how to signal numpy that the operation is "reorderable" (commutative?). The trick was providing `PyUFunc_ReorderableNone` as `identity` in the ufunc definition. I can see this to be present as far back …
=> [API] Set None as default axis for reduction operations

docs/_static/custom.css, docs/conf.py, docs/environment.yml
So I think the issue is due to a sphinx > 2 compatibility issue with numpydoc (https://github.com/numpy/numpydoc/issues/215). I included a workaround for that in the past in geopandas (https://github.com/geopandas/geopandas/pull/1299). 
But, it should normally now also be fixed in the rtd theme itself in the latest versions. The problem seems to be that we are getting an older version (I assume because rtd installs it from defaults). So testing if installing it in our specified env from conda-forge solves that.
=> DOC: fix style issue with numpydoc parameter names and sphinx_rtd_theme

asv.conf.json
Add cython, which is now needed to build pygeos, and update the python version. I also set conda-forge as channel, because defaults is typically a bit lagging behind (eg in GEOS version)
=> Update ASV configuration

CHANGELOG.rst, pygeos/creation.py, pygeos/predicates.py, pygeos/test/test_predicates.py, src/ufuncs.c
Closes #180
Since this is only available as a prepared function on the GEOS side, the question is what we do here:
- Automatically prepare the geometry within the `contains_properly` function (eg this can be done on the python side, by calling `pygeos.prepare` on the input before calling ``pygeos.lib.contains_properly``). 
- Still leave this as a responsibility to the user to provide prepared geometries (in which case I should probably add a custom error type on the C level so we can give a custom error message in python, because now I am just raising a GEOSException)
The second option is more consistent with the other predicates, but of course those all work out of the box for non-prepared geometries (so in terms of *usage*, the first option might look more consistent)
=> ENH: add contains_properly predicate function

CHANGELOG.rst, pygeos/strtree.py
I ran our STRtree benchmarks, but it didn't give any significant change (it might be that our benchmarks are too small / too "dummy" random geometries to notice a difference, if there would be one)
This came up in Shapely, where this was actually done wrong (set at size of geometry array, https://github.com/Toblerity/Shapely/pull/1064#discussion_r562376957). While this is not the case here, @dbaston mentioned that based on his experiments leaf size of 8 to 16 was optimal, and GEOS internally defauls to 10. So unless we have a good reason to deviate (@caspervdw?), probably best to just follow GEOS' default.
=> Change default STRtree leaf lize (node capacity) to 10

pyproject.toml
@brendan-ward I _think_ this should fix #294
Now that numpy 1.20 is released, we have the problem that in the Python 3.9 build we pinned numpy to 1.19 in the environment, but pygeos itself was still built against the latest (so a newer) numpy. And when it comes to building, numpy is forward compatible (built with older version will work with newer), but not the other way around
=> Update pin for numpy version for Python 3.9 in pyproject.toml

CHANGELOG.rst, docker/Dockerfile.arm64, src/ufuncs.c
Resolves #291 
We were using a `char` with a -1 sentinel value, which fails on ARM architectures because it is unsigned.  This PR assigns it to an `int` which is the proper return value for `GEOSGeomTypeId_r` in this case anyway.
=> Fix signed char portability issue

.github/workflows/test-linux.yml, appveyor.yml
GEOS 3.9.1 was recently [announced](https://lists.osgeo.org/pipermail/geos-devel/2021-February/010138.html). Bump the following GEOS versions:
- Github Actions: 3.9.0 -> 3.9.1
- AppVeyor: 3.8.1 -> 3.9.1
=> CI: bump versions to latest GEOS-3.9.1

pygeos/test/test_misc.py, src/lib.c
We are getting version test failures on GEOS master or latest on the `3.9.1` branch because the version string includes modifiers like `dev`.
This PR is one way to resolve that within C, by building up the string from the integer parts.  I'm not sure I like this option; it has the risk of being a tautology (i.e., version string is no longer a validity check against the tuple of version parts).
Do we want the version string to reflect the original string from GEOS with these modifiers?  This seems like it might be useful from a troubleshooting perspective.  In which case, we just need to modify the tests so that they ignore these modifiers, but we allow the versions to be a bit different: (3,9,1) => `3.9.1dev`
=> TST: Handle GEOS version strings with dev / beta qualifiers in the tests

pygeos/creation.py, pygeos/test/common.py, pygeos/test/test_creation.py, pygeos/test/test_geometry.py, src/geos.c, src/geos.h, src/pygeom.c, src/ufuncs.c
See #233 for a discussion. For GEOS 3.9 and before, we were able to construct a POINT (nan nan). In GEOS master, this is not possible anymore and it transforms to a POINT EMPTY. This caused some of our tests to fail.
These tests just use a point because it is the simplest geometry. Now I updated the tests so that they use linestrings and everything passes on my machine.
=> NaN equality tests for GEOS 3.10

pygeos/io.py, pygeos/test/test_io.py
Partially addresses #297 
Unfortunately, it is quite elaborate to emulate s390x on linux, so testing occurs on Travis.
I can trigger this manually from a test branch, see https://travis-ci.com/github/caspervdw/pygeos/jobs/487227201
=> Pin endianness in to_wkb tests

CHANGELOG.rst, pygeos/constructive.py, pygeos/enum.py, pygeos/strtree.py, pygeos/test/test_constructive.py
This fixes a minor bug in the docstring for buffer; it listed an invalid `join_style` option.
While I was at it, I made the enums lowercase to match their usage in the functions for usability, and added a validation of values to give better error message than what you get back now when a value isn't in an `IntEnum`.
Note: this changes the original `KeyError` that would have been emitted to a `ValueError`, which seems more appropriate in this case (it is the _value_ that is wrong; that it is a key in an `IntEnum` is an implementation detail).
=> ENH: Consolidate validation of enum values and raise ValueError on invalid values

setup.py
I have been scratching my head over linking issues over the past hour, and it appeared that `python setup.py clean` did not actually clean all the compiled libraries. Now it does.
=> Also clean build/lib.*/pygeos in setup.py clean

CHANGELOG.rst, pygeos/strtree.py
See https://github.com/pygeos/pygeos/pull/263#issuecomment-790463108. Removing it broke geopandas. I think it's easy to keep it a bit longer in pygeos for now (and we can still revert this before doing the next release)
=> Add back pygeos.strtree.VALID_PREDICATES for now

CHANGELOG.rst, benchmarks/benchmarks.py, pygeos/creation.py, pygeos/test/test_creation.py, src/geos.c, src/geos.h, src/strtree.c, src/ufuncs.c
This adds a ufunc for `box` based on the `create_box` function introduced in #272  and replaces the prior implementation in Python.
Also resolves #306 
Also resolves a latent bug in `create_box` because it was testing for equality to `NP_NAN` (which always fails) instead of using `npy_isnan()`.
This is about 2x as fast as the prior implementation:
```
benchmarks.ConstructiveSuite.time_box                                        8.76±0.3ms
benchmarks.ConstructiveSuite.time_box_prev                                   16.1±0.4ms
```
Some tests were adjusted slightly; the polygons returned by `box` are now in normalized form because `create_box` creates them that way.
The only bit that was a little awkward was that errors are not thrown by `create_box`; it always returns `NULL` when geometries …
=> Add box ufunc based on create_box C function

.travis.yml
This allows the `s390x` arch to fail in Travis-CI, since it is failing due to errors at the GEOS level.
=> TST: Allow s390 CI fail

pygeos/strtree.py, pygeos/test/test_strtree.py
We expect `max_distance` to be scalars but didn't correctly validate that.  This adds a check and associated test.
=> Raise ValueError on nonscalar max_distance parameter for STRtree::nearest_all

.travis.yml
See results here: https://travis-ci.com/github/pygeos/pygeos/builds/220415212
We needed to use the `matrix` directly in order to mark one of the runs for failure.
=> TST: Really allow s390x to fail on Travis CI

CHANGELOG.rst, pygeos/coordinates.py, pygeos/io.py, pygeos/linear.py, pygeos/test/test_coordinates.py, src/coords.c
This adds the option to return indices of coordinates in ``pygeos.get_coordinates``. 
In general I don't like the pattern of returning a different type depending on input parameters, but here it is such a simple solution to implement a large chunk of functionality, that I went for it anyway. `np.unique` does this too.
=> Enable "return_index" in get_coordinates

CHANGELOG.rst, pygeos/io.py, pygeos/test/test_io.py, src/geos.h, src/ufuncs.c
Resolves #320
For reasons stated in #320, it is problematic to raise exceptions when deserializing invalid geometries from formats such as WKB.  This provides a way to gracefully read those in, raise a warning, and allow the user to filter them out instead of failing hard.
This adds a new enum value `PGWARN_GEOS_EXCEPTION` which is used to raise the GEOS exception as a warning instead of an exception.
=> Raise warning and return None on invalid WKB/WKT instead of raising exception

CHANGELOG.rst, pygeos/constructive.py, pygeos/test/test_constructive.py, src/fast_loop_macros.h, src/ufuncs.c
Follow-up on https://github.com/pygeos/pygeos/pull/275, adding the "full" version.
Current behaviour: returns 4 collections (polygons, dangles, cut edges, invalid rings):
```
In [17]: lines = np.array([pygeos.Geometry("LINESTRING (0 0, 1 1)"), pygeos.Geometry("LINESTRING (0 0, 0 1, 1 1)"), pygeos.Geometry("LINESTRING (0 1, 1 1)")])
In [18]: pygeos.lib.polygonize_full(lines)
Out[18]: 
(<pygeos.Geometry GEOMETRYCOLLECTION (POLYGON ((1 1, 0 0, 0 1, 1 1)))>,
<pygeos.Geometry GEOMETRYCOLLECTION EMPTY>,
<pygeos.Geometry GEOMETRYCOLLECTION (LINESTRING (0 1, 1 1))>,
<pygeos.Geometry GEOMETRYCOLLECTION EMPTY>)
```
=> ENH: add polygonize_full

CHANGELOG.rst, pygeos/io.py, pygeos/test/test_io.py, src/ufuncs.c
I noticed issue #54 was pushed to a next milestone and thus decided to put some work into it.
This PR adds a `to_shapely()` function and improves the `from_shapely()` function to also work when the GEOS versions of both library do not match, by going through the WKB format (similarly to how geopandas handles things).
This implementation is implemented purely in python, as I do not know how we should create shapely objects from C.
I still believe it is worth adding, as this fills a "gap" in the current pygeos pipeline, and we can still optimize it without affecting the public API, later down the road...
Remarks / TODO:
Let's keep the to_* and from_* functions simple.
Not implementing this for now. If anyone wants to try to get an even faster conversion, feel free...
I do not think this is …
=> to_shapely and from_shapely updates

pygeos/linear.py
This closes #155 (along with #326 which releases the GIL for geometry-creating functions)
=> Release the GIL in shared_paths (missing decorator)

pygeos/coordinates.py
Fixes the formatting of the final examples: https://pygeos.readthedocs.io/en/latest/coordinates.html#pygeos.coordinates.get_coordinates
=> DOC: Fix docstring for get_coordinates

.github/workflows/test-linux.yml
According to the [Ubuntu release schedule](https://wiki.ubuntu.com/Releases), Ubuntu Xenial 16.04 is to reach it's end of standard support in a few days. Upgrading to [`ubuntu-latest`](https://github.com/actions/virtual-environments), which is currently an alias to Ubuntu Focal 20.04.
Note that `ubuntu-latest` is consistently used for `test-conda.yml` and `lint.yml` workflows.
=> TST: ubuntu-16.04 about to reach EOL; upgrade to ubuntu-latest

CHANGELOG.rst, pygeos/_geometry.pyx, pygeos/_geos.pxd, pygeos/creation.py, pygeos/test/test_creation.py, pygeos/test/test_creation_indices.py, src/ufuncs.c
Follow up from #326 .
Now `polygons` only takes 1 array of rings if used in combination with `indices`.
Also now the collection constructor raise errors if there are any indices missing (see #345). It was easier to implement the Polygons in that way.
=> Merge polygons_1d into collections_1d + finish implementation for rls 0.10

pygeos/test/test_measurement.py, src/coords.c, src/geos.c, src/pygeom.c, src/ufuncs.c
As noticed in https://github.com/pygeos/pygeos/pull/334/files#r627371656, we were mostly using the bitwise operators (`&`, `|`) instead of the logical operators (`&&`, `||`). See https://en.wikipedia.org/wiki/Operators_in_C_and_C%2B%2B#Logical_operators 
In most cases this probably won't make much difference in practice, but apart from the logical operators being more correct usage, an important difference is that those short-circuit. And `hausdorff_distance` was one case were we relied on short-circuiting (to avoid passing NULL to `GEOSisEmpty`; the test case I added currently segfaults)
=> Fix use of C logical operator

CHANGELOG.rst, pygeos/linear.py, pygeos/test/test_linear.py, src/ufuncs.c
This is initial work to expose the `GEOSNearestPoints_r` function. There are however some design questions to decide on.
- The GEOS function returns a lenght-2 `CoordSequence`, so we need to wrap/unwrap that in some way for the actual return value
- Shapely exposes it as [`shapely.ops.nearest_points`](https://shapely.readthedocs.io/en/stable/manual.html#nearest-points) which returns a tuple of 2 Point geometries.
- The R spatial packages (`sf`) have a [`st_nearest_points`](https://r-spatial.github.io/sf/reference/st_nearest_points.html) to expose this, which returns this as a two-point LineString. 
- PostGIS doesn't expose this GEOS function, but they do have a [`ST_ShortestLine`](https://postgis.net/docs/ST_ShortestLine.html) with similar functionality, also returning a line of two …
=> ENH: Add shortest_line (nearest_points) ufunc

docs/conf.py, docs/constructive.rst, pygeos/constructive.py, pygeos/coordinates.py, pygeos/creation.py, pygeos/geometry.py, pygeos/io.py, pygeos/linear.py, pygeos/measurement.py, pygeos/predicates.py, pygeos/set_operations.py, pygeos/strtree.py
In #314 we decided to add `minimum_rotated_rectangle` as an alias for `oriented_envelope`. Now this is implemented as a duplicate (with duplicate docstrings & code).
I think it is better to not have "two things to do something". We do not have to consider legacy so there is no reason for having the duplicate there.
So instead I do `minimum_rotated_rectangle = oriented_envelope`, and hide the duplicate docstring.
Also it is not necessary (and we currently do it wrong) to show the `default` in the docstring under numpydoc convention. From https://numpydoc.readthedocs.io/en/latest/format.html#parameters: 
> Optional keyword parameters have default values, which are displayed as part of the function signature. They can also be detailed in the description: (...) or as part of the type, instead …
=> Remove minimum_rotated_rectangle duplicate + fix docstrings

MANIFEST.in
Fixes #284 
The cythonized .c files should not be included in a source distribution.
=> Exclude Cythonized .c files from distributions

.github/workflows/test-linux.yml, ci/install_geos.sh
GEOS renamed their git development head branch from 'master' to 'main' in March 2021 ([ref](https://lists.osgeo.org/pipermail/geos-devel/2021-March/010193.html)).
=> TST: rename head branch for GEOS from 'master' to 'main'

pygeos/test/common.py
This should fix https://github.com/conda-forge/pygeos-feedstock/pull/38 for the next release.
=> FIX: Testing on Pypy

.github/workflows/release.yml
@caspervdw what do you think of this?
We have been happily using this for GeoPandas and some related packages (https://github.com/geopandas/geopandas/blob/master/.github/workflows/release_to_pypi.yml). 
Of course, here the scope is more limited (I didn't include releasing to PyPI, as for that ideally you directly upload both sdist and wheels), making this less useful. But automating the sdist creation, and uploading it to a new GitHub release still could be useful,I think (not fully sure, the sdist creation is also not a lot of work, you only need to be careful about not including eg cythonized files, which is safer on a new checkout in the github action). 
The workflow would then be: 1) tag locally and push the tag (as before), 2) let the action run and create the github release, 3) …
=> Release workflow: automate sdist creation / GitHub release

CHANGELOG.rst, pygeos/test/test_geometry.py, src/pygeom.c
Closes #373 
Apparently, Numpy treats NULL the same as None in object-dtype arrays.
=> FIX: Handle NULL in object-dtype arrays

CHANGELOG.rst, pygeos/tests/test_predicates.py, src/ufuncs.c
Closes #337
Turns out GEOS is perfectly capable to determine whether a linearring is closed. Our code was just in the way.
=> Handle linearrings in is_closed

CHANGELOG.rst, pygeos/decorators.py, pygeos/io.py, pygeos/tests/test_io.py, src/geos.c, src/geos.h, src/ufuncs.c
This implements to/from geojson ufuncs using the new GeoJSON reader and writer from GEOS 3.10.
There are a few open issues, we get crashes on:
```
>>> pygeos.from_geojson('{"no": "geojson"}')
python: /home/casper/code/geos/include/geos/vend/json.hpp:20363: const value_type& geos_nlohmann::basic_json<ObjectType, ArrayType, StringType, BooleanType, NumberIntegerType, NumberUnsignedType, NumberFloatType, AllocatorType, JSONSerializer, BinaryType>::operator[](T*) const [with T = const char; ObjectType = std::map; ArrayType = std::vector; StringType = std::__cxx11::basic_string<char>; BooleanType = bool; NumberIntegerType = long int; NumberUnsignedType = long unsigned int; NumberFloatType = double; AllocatorType = std::allocator; JSONSerializer = geos_nlohmann::adl_serializer; BinaryType = …
```
=> [Done] GeoJSON IO for GEOS 3.10

.github/workflows/test-pip.yml
I noticed that Python 3.10 is not available on the win32 test runner and that numpy 1.21.3 doesn't supply a wheels for win32.
So I reverted the versions a bit to speed up our build process.
=> Revert Win32 CI version for faster builds

CHANGELOG.rst, pygeos/decorators.py, pygeos/io.py, pygeos/may_segfault.py, pygeos/tests/test_io.py, pygeos/tests/test_misc.py
In #413  we concluded that from_geojson segfaults for some inputs only when GEOS is built in Debug mode.
Now, a CI failed (https://github.com/pygeos/pygeos/runs/4059627215?check_suite_focus=true) which builds GEOS in Release mode. So I think it is best to stay on the safe side and reinstate the segfault protection here.
Related GEOS Ticket has been solved in main already:
- https://trac.osgeo.org/geos/ticket/1138
- https://github.com/libgeos/geos/pull/498
=> [Done] Reinstate may_segfault for from_geojson

.github/workflows/release.yml, .github/workflows/test-pip.yml
GEOS version upgrades:
- 3.6.4 -> 3.6.5 [announcement](https://lists.osgeo.org/pipermail/geos-devel/2020-December/009994.html)
- <s>3.8.1 -> 3.8.2 [announcement](https://lists.osgeo.org/pipermail/geos-devel/2021-April/010201.html)</s>
- 3.9.1 -> 3.9.2 [announcement](https://lists.osgeo.org/pipermail/geos-devel/2021-November/010526.html)
- 3.10.0 -> 3.10.1 [announcement](https://lists.osgeo.org/pipermail/geos-devel/2021-November/010556.html)
=> CI: upgrade GEOS versions, fix "Run doctests"

docker/Dockerfile.valgrind, pygeos/tests/test_strtree.py, src/strtree.c
This fixes a couple memory leaks lurking in our tests and moves cleanup of some of the vectors we create during tree operations so that they are correctly cleaned up (hopefully; our tests don't cover these all).
This updates the `Dockerfile.valgrind` to build GEOS 3.10, so we can test against the latest features.
This also uncovered what looks like a memory leak in GEOS related to prepared geometry predicates, when those geometries have nan coordinates.  These memory leaks are present in our latest valgrind results, e.g.,
```
Valgrind has detected a memory leak:
**1** 
**1** **********************************************************************
**1** pygeos/tests/test_strtree.py::test_query_predicate_errors[touches]
**1** ******************************************************************** …
```
=> BUG: Fix STRtree memory leaks

.github/workflows/test-pip.yml, CHANGELOG.rst, pygeos/measurement.py, pygeos/testing.py, pygeos/tests/common.py, pygeos/tests/test_constructive.py, pygeos/tests/test_measurement.py, pygeos/tests/test_predicates.py, pygeos/tests/test_strtree.py
Closes #357 - tests with GEOS 3.10.1 now pass without warnings.
There are some issues that should be reported upstream:
- binary predicates on empty geometries set an invalid flag
- voronoi_polygons on a point set an invalid flag
- hausdorff_distance sets an invalid flag (in our seemingly normal test)
- offset_curve on an empty linestring set an invalid flag
=> Solve RuntimeWarnings in tests

CHANGELOG.rst, pygeos/_geometry.pyx, pygeos/_geos.pxd, pygeos/_pygeos_api.pxd, pygeos/tests/test_creation.py, pygeos/tests/test_creation_indices.py, src/c_api.c, src/c_api.h, src/geos.c, src/geos.h, src/lib.c, src/ufuncs.c
Experiment in using the new `GEOSCoordSeq_copyFromBuffer` for creating CoordinateSequences instead of setting each ordinate individually.
This requires GEOS 3.10, so will require https://github.com/pygeos/pygeos/issues/255 to use this in cython.
I was benchmarking it with the US census polygons ([tl_2019_us_zcta510.zip](https://catalog.data.gov/dataset/tiger-line-shapefile-2019-2010-nation-u-s-2010-census-5-digit-zip-code-tabulation-area-zcta5-na), 33144 (multi)polygons, with on average ~1200 coordinates per ring).
Focusing on LinearRing creation (the actual creation of (Multi)Polygons from those rings will of course see less of a difference):
I saved the coordinates and offsets in a numpy file, to load them again to benchmark (see …
=> PERF: Use GEOSCoordSeq_copyFromBuffer for creating simple geometries

.github/workflows/release.yml, CHANGELOG.rst
manylinux2010 wheels are built for CentOS 6, which reached end of life in November 2020 (see https://www.python.org/dev/peps/pep-0599/)
So it is good to move on to manylinux2014 which is for CentOS 7.
Numpy also started doing this for their cp310 wheels; because of this our cp310 builds are compiling numpy. This PR solves that issue too.
=> Move to manylinux2014 wheels

.github/workflows/release.yml, .github/workflows/test-pip.yml, .travis.yml, docker/Dockerfile.valgrind, pygeos/tests/test_io.py
The motivation for this is from GeoPandas and pygeos installed via pip:
```
../../../../tmp/py39/lib/python3.9/site-packages/geopandas/_compat.py:111
/tmp/py39/lib/python3.9/site-packages/geopandas/_compat.py:111: UserWarning: The Shapely GEOS version (3.10.2-CAPI-1.16.0) is incompatible with the GEOS version PyGEOS was compiled with (3.10.1-CAPI-1.16.0). Conversions between both will be slow.
warnings.warn(
```
While Shapely-2.0 is not out yet, it would be nice to have binary wheels on PyPI that have he same GEOS version as Shapely.
=> MAINT: upgrade release and tests to use GEOS 3.10.2

.github/workflows/release.yml, .github/workflows/test-pip.yml, .travis.yml, docker/Dockerfile.valgrind
See https://lists.osgeo.org/pipermail/geos-devel/2022-June/010685.html for announcement of several patch releases.
Builds for releases have changed to GEOS 3.10.3 (see also #450).
Also, build sdist using PyPA's [build](https://github.com/pypa/build) tool.
=> CI: upgrade GEOS patch versions for tests, use GEOS 3.10.3 for release

.pre-commit-config.yaml, pygeos/io.py, pygeos/tests/test_io.py, src/ufuncs.c
To allow to have pygeos and shapely 2 installed together and interoperable (useful for pygeos users that have to gradually migrate to shapely 2)
=> Fix to/from_shapely for compat with shapely 2

.pre-commit-config.yaml, pygeos/io.py
Since we have had several reports of subtle crashes in certain cases when using wheels that seem to be related to this sharing of GEOS pointers (for example https://github.com/pygeos/pygeos/issues/447, https://github.com/pygeos/pygeos/issues/377, https://github.com/pygeos/pygeos/issues/122, https://github.com/geopandas/geopandas/issues/2551, https://github.com/geopandas/geopandas/issues/2613#issuecomment-1290387118), it seems safer to restrict this fastpath to conda-only. 
This shouldn't impact results, only a slowdown in shapely / pygeos conversion. 
This also doesn't actually check that you are using a shapely and pygeos conda package, only if you are in a python managed by conda (but you can still install wheels into a conda environment).
=> Only use fastpath in to/from_shapely conversion when using conda
